### PR TITLE
Enable CI on windows and fix it.

### LINKED ISSUE #316: Windows/Cygwin: hygienic check fails for some packages
It looks like an [old issue](https://github.com/ocaml/opam-repository/issues/6224) has popped up again in `ocamlbuild` `0.14.1`.
For some packages on Windows/Cygwin (Mingw toolchain), the hygienic check fails, e.g., for `mtime` `1.3.0`:
```
mkdir 'C:\Opt\OCaml64\home\kayuwe.kirstein\.opam\4.13.1+mingw64\.opam-switch\build\mtime.1.3.0\_build'
Das System kann den angegebenen Pfad nicht finden.
''ocamlfind ocamlopt unix.cmxa -I 'C:/Opt/OCaml64/home/kayuwe.kirstein/.opam/4.13.1+mingw64/lib\ocamlbuild' 'C:/Opt/OCaml64/home/kayuwe.kirstein/.opam/4.13.1+mingw64/lib\ocamlbuild/ocamlbuildlib.cmxa' -linkpkg myocamlbuild.ml 'C:/Opt/OCaml64/home/kayuwe.kirstein/.opam/4.13.1+mingw64/lib\ocamlbuild/ocamlbuild.cmx' -o myocamlbuild.exe
SANITIZE: a total of 3 files that should probably not be in your source tree
  has been found. A script shell file
  "C:\\Opt\\OCaml64\\home\\kayuwe.kirstein\\.opam\\4.13.1+mingw64\\.opam-switch\\build\\mtime.1.3.0\\_build/sanitize.sh"
  is being created. Check this script and run it to remove unwanted files or
  use other options (such as defining hygiene exceptions or using the
  -no-hygiene option).
IMPORTANT: I cannot work with leftover compiled files.
ERROR: Leftover object files:
  File myocamlbuild.o in _build has suffix .o
ERROR: Leftover OCaml compilation files:
  File myocamlbuild.cmi in _build has suffix .cmi
  File myocamlbuild.cmx in _build has suffix .cmx
Exiting due to hygiene violations.
pkg.ml: [ERROR] cmd ["ocamlbuild" "-use-ocamlfind" "-classic-display" "-j" "4" "-tag" "debug"
     "-build-dir" "_build" "opam" "pkg/META" "CHANGES.md" "LICENSE.md"
     "README.md" "src/mtime.a" "src/mtime.cmxs" "src/mtime.cmxa"
     "src/mtime.cma" "src/mtime.cmx" "src/mtime.cmi" "src/mtime.mli"
     "src/mtime_top.a" "src/mtime_top.cmxs" "src/mtime_top.cmxa"
     "src/mtime_top.cma" "src/mtime_top.cmx" "src/mtime_top_init.ml"
     "doc/index.mld" "src-os/mtime_clock.a" "src-os/mtime_clock.cmxs"
     "src-os/mtime_clock.cmxa" "src-os/mtime_clock.cma"
     "src-os/mtime_clock.cmx" "src-os/mtime_clock.cmi"
     "src-os/mtime_clock.mli" "src-os/dllmtime_clock_stubs.dll"
     "src-os/libmtime_clock_stubs.a" "test-os/min_os.ml"]: exited with 1
```
I am not sure whether the first error message on not finding the build folder is a serious failure.
Executing `sanitize.sh` does not help, I guess `opam install mtime` regenerates the object files every time.

Observed on Windows 10, Cygwin/Mingw (Ocaml for Windows) for OCaml `4.13.1+mingw64`.
My current workaround is downgrading `ocamlbuild` to `0.14.0`.

### PR DESCRIPTION
**Pull request by hhugo**
This is a somewhat minimal list of changes to make the testsuite pass on windows.
If you look at the CI jobs, you should see that the testsuite pass under windows.

Includes:
- part of #70 https://github.com/ocaml/ocamlbuild/pull/70/commits/62c40ca26173f794790243d608d6415d0a64a6ce
- part of #323 

Probably fix #316

### CODE REVIEW

File: testsuite/internal.ml [hunk 1]
```diff
@@ -182,21 +184,21 @@ let () = test "CmxsStubLink"
...
+let () =\n\
+  dispatch begin function\n\
+  | After_rules ->\n\
+      dep [\"record_foo_stubs\"] [\"src/libfoo_stubs.a\"];\n\
+      flag_and_dep\n\
+        [\"link\"; \"ocaml\"; \"link_foo_stubs\"] (P \"src/libfoo_stubs.a\");\n\
+      flag [\"library\"; \"ocaml\";           \"record_foo_stubs\"]\n\
+        (S ([A \"-cclib\"; A \"-lfoo_stubs\"]));\n\
+  | _ -> ()\n\
+  end\n\
```
Comment (gasche) [inline testsuite/internal.ml:201]: Urgh, can you use quoted literals instead to avoid the many escapes here? (If there is a problem with `\r\n` somehow, we could inject a small helper function that removes the `\r`.)

File: src/my_std.ml [hunk 2]
```diff
@@ -279,7 +279,7 @@ let sys_command =
   match Sys.os_type with
   | "Win32" -> fun cmd ->
       if cmd = "" then 0 else
-      let cmd = "bash --norc -c " ^ Filename.quote cmd in
+      let cmd = "bash --norc -c " ^ Filename.quote cmd ^ " 2>&1" in
```
Comment (gasche) [inline src/my_std.ml:282]: Can you explain why we need this change?

**Review by gasche — COMMENTED** [review]
This looks okay overall, see one question on the stderr rediction.

I'm not fond of the generalized use of explicit newline quoting in string literals in the testsuite, I find that it really hurts readability. Can we use quoted string literals instead?

File: testsuite/internal.ml (hunk 1 above)
Comment (hhugo) [reply testsuite/internal.ml]: I've pushed https://github.com/ocaml/ocamlbuild/pull/329/commits/0f2342a2236c60252b638617c9c11752a7f6189c

File: src/my_std.ml (hunk 2 above)
Comment (hhugo) [reply src/my_std.ml:282]: I'm not happy with this change but it makes the testsuite pass.

I think the explanation is as follow:
- if `is_degraded` or Sys`.win32` is true, `execute_many` falls back to `sys_command` to implement `execute_many`.
- otherwise, the logic from `Ocamlbuild_executor.execute` is used, which reads both stderr and stdout into a `job_buffer`.
- The testuite sometime expect some output on stdout.  

I'm still looking into a better solution.

Comment (hhugo) [reply src/my_std.ml]: I've moved the stderr redirection to `command.ml` where I think it belongs and added a small comment.

Comment (gasche) [reply src/my_std.ml]: I went to look at the code of ocamlbuild_executor to understand what is going on. `ocamlbuild_executor` does not just redirect stderr into stdout, it lets the command write to different places *and then* on job termination it adds stdout, then stderr, to the job buffer, in that order. The change that you implemented does not match this behavior, it only works for commands that have only stdout or only stderr output.

Comment (gasche) [reply src/my_std.ml]: Out of curiosity: in the `execute_many` definition, have you tried removing the "or we are on Windows" condition, to get the ocamlbuild_executor logic to run also on Windows? When ocamlbuild was first written, I think the Windows support in stdlib and Unix was weaker than it is now, there is a small chance that removing those alternate paths could work today.

(We could probably also get rid of the "is_degraded" notion, which I think was designed to let ocamlbuild build the compiler in constrained environments. ocamlbuild is not considered as build system for the OCaml compiler anymore, so maybe we could forget about this case altogether. But this is more work than I was considering putting in ocamlbuild again.)

File: src/shell.ml [hunk 3]
```diff
@@ -39,7 +39,7 @@ let run args target =
   let cmd = String.concat " " (List.map quote_filename_if_needed args) in
   if !*My_unix.is_degraded || Sys.os_type = "Win32" then
     begin
-      Log.event cmd target Tags.empty;
+      if false then Log.event cmd target Tags.empty;
```
Comment (kit-ty-kate) [inline src/shell.ml:42]: Why is this disabled?
```suggestion
      Log.event cmd target Tags.empty;
```

File: testsuite/ocamlbuild_test.ml [hunk 4]
```diff
@@ -435,6 +439,17 @@ let print_colored header_color header name body_color body =
...
+  if not (Sys.file_exists dir)
+  then
+    try Unix.mkdir dir 0o750 with _ -> ()
+
+let rec mkdir_p dir =
+  if Sys.file_exists dir then ()
+  else begin
+      mkdir_p (Filename.dirname dir);
+      try_mkdir dir
+    end
```
Comment (kit-ty-kate) [inline testsuite/ocamlbuild_test.ml:452]:
```suggestion
let rec mkdir_p dir =
  if not (Sys.file_exists dir) then begin
    mkdir_p (Filename.dirname dir);
    Unix.mkdir dir 0o750;
  end
```

File: testsuite/ocamlbuild_test.ml [hunk 5]
```diff
@@ -32,10 +32,14 @@ let print_string_list_blank = print_list_blank pp_print_string
 
 let exists filename =
   try ignore(Unix.stat filename); true
-  with Unix.Unix_error ((Unix.ENOENT),_,_) -> false
+  with Unix.Unix_error ((Unix.ENOENT),_,_) ->
+    if Sys.win32
+    then Sys.file_exists filename
+    else false
```
Comment (kit-ty-kate) [inline testsuite/ocamlbuild_test.ml:38]: why not simply use `Sys.file_exists` on all platforms?
```suggestion
  Sys.file_exists filename
```

**Review by kit-ty-kate — COMMENTED** [review]
Looks fine on first glance with my minimal Windows experience.

cc-ing more experienced Windows users @dra27 @jonahbeckford

File: src/shell.ml (hunk 3 above)
Comment (hhugo) [reply src/shell.ml:42]: It make the testsuite fail because it output `cmd` on stdout.
I wonder if we should prefix the command with `"+ "` similar to what is done in non-degraded mode. The testsuite filters theses lines out already.

File: testsuite/ocamlbuild_test.ml (hunk 5 above)
Comment (hhugo) [reply testsuite/ocamlbuild_test.ml:38]: I don't know how the behavior defer, I wanted to avoid changing the behavior in non windows as much as possible. But it's probably fine inside the testsuite.

Comment (hhugo) [reply testsuite/ocamlbuild_test.ml]: applied

File: src/shell.ml (hunk 3 above)
Comment (hhugo) [reply src/shell.ml]: I've added the `+ ` prefix

File: src/my_std.ml (hunk 2 above)
Comment (hhugo) [reply src/my_std.ml]: > I went to look at the code of ocamlbuild_executor to understand what is going on. `ocamlbuild_executor` does not just redirect stderr into stdout, it lets the command write to different places _and then_ on job termination it adds stdout, then stderr, to the job buffer, in that order. The change that you implemented does not match this behavior, it only works for commands that have only stdout or only stderr output.

Looking at the code quickly, my impression is that it can interleave stdout and stderr. In the main `loop`, you can see
```
chrfds, do_read ~loop:false;
```
which tries to read any both stdout and stderr and push the content to `job_buffer`.

Maybe I'm misunderstanding the logic.

Comment (gasche) [reply src/my_std.ml]: Ok, this suggests that I misunderstood, and there may be no good way to ensure that we get the same output. In that context I am okay with your current choice even though it is sort of a hack.

**Comment by gasche** [comment]
Ideally what I would like to do is to get good Windows support without making the codebase worse than it already is. I think that the current PR you propose is okay in this respect, the changes are relatively minimal and at the same time justified, and the risk of regression for non-Windows users is low. I propose to merge it and build up from there.

On the other hand I am more worried about the fdopen patches in #330, which look like a mix of good ideas (I like getting rid of the "or is win32" case in the "is degraded?" test), inscrutable hacks, and a things in the middle, and was never really tested on non-Windows systems if I understand correctly. Taking the good pieces out of it is an excellent idea, and maybe all of it is good and I just don't understand it yet. But making our codebase harder to understand (obscure changes with little explanations and no commit message) is getting convenience right now but also even more pain later, so I would not be in favor.

Note: I noticed the same `Be consistent!` comment in the present PR and in the .patch file somewhere. Are you the author of all the changes in the current PR? If not, are reused fragment properly credited and do they have a compatible software license?

**Review by gasche — APPROVED** [review]

**Comment by hhugo** [comment]
https://github.com/ocaml/ocamlbuild/pull/329/commits/00b92ab0f67698e3d85be72f02c68d00a3374ec6 was extracted from an old PR  #70 -> https://github.com/ocaml/ocamlbuild/pull/70/commits/62c40ca26173f794790243d608d6415d0a64a6ce

**Comment by gasche** [comment]
Could you cherry-pick that commit (or amend the author information on your own commit) to properly credit fdopen in the metadata?

**Comment by kit-ty-kate** [comment]
> @kit-ty-kate are you okay with merging this? My reasoning is: the patch looks okay, the potential for non-Windows regression is minimal, and I want to make it as easy as reasonably possible for @hhugo (or of course anyone else) to improve the state of ocamlbuild on Windows.

Merging is fine as long as we remember to not release before getting the double-check/approval of the two people i've cc'd above. I'd like to especially double-check the change made to `plugin-lib/ocamlbuild_unix_plugin.ml` and `src/command.ml`, which seem a bit fragile, especially as:
- `bash` could be present in the environment, without it being linked to an MSYS2 or Cygwin installation (e.g. some programs like some git installation ship with `bash.exe`)
- I'm not certain the quoting used is always correct with cmd.exe but I may be wrong. In particular I would like to understand this comment from 8 years ago: https://github.com/ocaml/ocamlbuild/pull/70#issuecomment-223121978
- Calls to `bash` uses `--noprofile` in https://github.com/ocaml/ocamlbuild/pull/330, is there a reason why this has not been done here too?

File: src/my_std.ml (hunk 2 above)
Comment (hhugo) [reply src/my_std.ml]: > Out of curiosity: in the `execute_many` definition, have you tried removing the "or we are on Windows" condition, to get the ocamlbuild_executor logic to run also on Windows? When ocamlbuild was first written, I think the Windows support in stdlib and Unix was weaker than it is now, there is a small chance that removing those alternate paths could work today.
> 
> (We could probably also get rid of the "is_degraded" notion, which I think was designed to let ocamlbuild build the compiler in constrained environments. ocamlbuild is not considered as build system for the OCaml compiler anymore, so maybe we could forget about this case altogether. But this is more work than I was considering putting in ocamlbuild again.)

Done in #333 and #332
